name: smart_home_security
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_circle_color_picker: ^0.3.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/